language: node_js
dist: xenial
sudo: required
addons:
  chrome: stable
  sauce_connect: true
node_js:
  - "11.10"
git:
  depth: 10
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
  - yarn run bootstrap
script:
  - (cd packages/library && yarn run build:starterkit)
  - (cd packages/library && yarn test)
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then
      (cd packages/library && yarn run test:sauce);
    fi
  - (cd packages/builder && yarn run build)
  - (cd packages/builder && yarn test)
after_success:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      (cd packages/builder && yarn run deploy);
    fi
