name: Build
on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn run bootstrap
      - run: (cd packages/library && yarn build:starterkit)
      - run: (cd packages/library && yarn test)
