name: Build
on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    name: Build and test library and builder

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
          scVersion: 4.6.2
      - run: yarn
      - run: yarn run bootstrap
      - run: (cd packages/library && yarn build:starterkit)
      - run: (cd packages/library && yarn test)
      - run: (cd packages/library && yarn test:sauce)
        if: ${{ github.event_name == 'push' }}
      - run: (cd packages/builder && yarn run build)
      - run: (cd packages/builder && yarn test)
